### ISSUE TITLE
Can you add paper address corresponding this code?

### ISSUE THREAD

**Issue by OliverZhuo** [pratham16/community-detection-by-seed-expansion#1]

**Comment by pratham16cse** [comment]
Thank you for your interest. Here is the link: https://dl.acm.org/doi/pdf/10.1145/3110025.3116193

I am not able to recover the account to which this repository is added. Requesting you to close the issue if solved.

Thanks,
Prathamesh

**Comment by OliverZhuo** [comment]
OK,got it.

Thank you very much,and I‘ve closed the issue.
